import { CATEGORIES,getCategory } from "../content/categories.mjs";import { getQuestion } from "./quiz-core.mjs";import { clampNumber,isIsoDate,normalizeMultiline,normalizeText,safeJsonParse,uniqueStrings } from "./text-core.mjs";
export const STORAGE_VERSIONS=Object.freeze({sessions:1,leaderboard:1,bookmarks:1,preferences:1});export const STORAGE_LIMITS=Object.freeze({sessions:40,leaderboard:20,bookmarks:50,importBytes:512*1024});
export function normalizeSession(v){if(!v||typeof v!=="object"||v.version!==1)return null;const id=normalizeText(v.id,100),mode=v.mode==="sprint"?"sprint":v.mode==="practice"?"practice":"",questionIds=uniqueStrings(v.questionIds,{maxItems:50,maxLength:80}).filter(getQuestion);if(!id||!mode||!questionIds.length||!isIsoDate(v.completedAt))return null;const answers=Array.isArray(v.answers)?v.answers.filter(a=>a&&questionIds.includes(a.questionId)).slice(0,questionIds.length).map(a=>({questionId:a.questionId,selectedIndex:Number.isInteger(a.selectedIndex)?a.selectedIndex:null,correct:Boolean(a.correct),answeredAt:isIsoDate(a.answeredAt)?a.answeredAt:v.completedAt,elapsedMs:Math.round(clampNumber(a.elapsedMs,0,3600000,0))})):[];const correct=answers.filter(a=>a.correct).length,total=questionIds.length;const categoryStats=Array.isArray(v.categoryStats)?v.categoryStats.filter(e=>e&&CATEGORIES.some(c=>c.id===e.category)).map(e=>({category:e.category,correct:Math.round(clampNumber(e.correct,0,100,0)),total:Math.round(clampNumber(e.total,0,100,0)),accuracy:Math.round(clampNumber(e.accuracy,0,100,0))})):[];return{version:1,id,mode,packId:normalizeText(v.packId,80)||"foundations",seed:normalizeText(v.seed,120),startedAt:isIsoDate(v.startedAt)?v.startedAt:v.completedAt,completedAt:v.completedAt,durationSeconds:Math.round(clampNumber(v.durationSeconds,0,86400,0)),remainingSeconds:mode==="sprint"?Math.round(clampNumber(v.remainingSeconds,0,90,0)):null,questionIds,answers,correct,total,accuracy:total?Math.round(correct/total*100):0,score:Math.round(clampNumber(v.score,0,100000,correct*100)),categoryStats}}
export function normalizeSessionsPayload(value){const p=typeof value==="string"?safeJsonParse(value,null):value;if(!p||typeof p!=="object"||p.version!==1)return{version:1,items:[]};const items=[],seen=new Set();for(const c of Array.isArray(p.items)?p.items:[]){const s=normalizeSession(c);if(!s||seen.has(s.id))continue;seen.add(s.id);items.push(s)}items.sort((a,b)=>Date.parse(b.completedAt)-Date.parse(a.completedAt));return{version:1,items:items.slice(0,40)}}
export function addSession(payload,session){const n=normalizeSessionsPayload(payload),next=normalizeSession(session);return next?normalizeSessionsPayload({version:1,items:[next,...n.items.filter(i=>i.id!==next.id)]}):n}
export function normalizeInitials(v){return normalizeText(v,32).toUpperCase().replace(/[^A-Z]/g,"").slice(0,4)}
export function normalizeLeaderboardPayload(value){const p=typeof value==="string"?safeJsonParse(value,null):value;if(!p||typeof p!=="object"||p.version!==1)return{version:1,items:[]};const items=[],seen=new Set();for(const c of Array.isArray(p.items)?p.items:[]){if(!c||typeof c!=="object")continue;const id=normalizeText(c.id,100),initials=normalizeInitials(c.initials);if(!id||!initials||seen.has(id)||!isIsoDate(c.completedAt))continue;seen.add(id);items.push({id,initials,score:Math.round(clampNumber(c.score,0,100000,0)),correct:Math.round(clampNumber(c.correct,0,100,0)),total:Math.round(clampNumber(c.total,1,100,1)),accuracy:Math.round(clampNumber(c.accuracy,0,100,0)),remainingSeconds:Math.round(clampNumber(c.remainingSeconds,0,90,0)),completedAt:c.completedAt})}items.sort((a,b)=>b.score-a.score||Date.parse(a.completedAt)-Date.parse(b.completedAt));return{version:1,items:items.slice(0,20)}}
export function addLeaderboardEntry(payload,session,initials){const ni=normalizeInitials(initials);if(!ni||!session||session.mode!=="sprint")return normalizeLeaderboardPayload(payload);const e={id:`${session.id}-${ni}`,initials:ni,score:session.score,correct:session.correct,total:session.total,accuracy:session.accuracy,remainingSeconds:session.remainingSeconds??0,completedAt:session.completedAt},cur=normalizeLeaderboardPayload(payload);return normalizeLeaderboardPayload({version:1,items:[e,...cur.items.filter(i=>i.id!==e.id)]})}
export function normalizeBookmarksPayload(value){const p=typeof value==="string"?safeJsonParse(value,null):value;if(!p||typeof p!=="object"||p.version!==1)return{version:1,items:[]};return{version:1,items:uniqueStrings(p.items,{maxItems:50,maxLength:80}).filter(getQuestion)}}
export function toggleBookmark(payload,id){const cur=normalizeBookmarksPayload(payload);if(!getQuestion(id))return cur;const items=cur.items.includes(id)?cur.items.filter(x=>x!==id):[id,...cur.items];return normalizeBookmarksPayload({version:1,items})}
export function calculateProgress(value){const sessions=normalizeSessionsPayload(value).items,map=new Map(CATEGORIES.map(c=>[c.id,{category:c.id,correct:0,total:0}]));let correct=0,total=0,bestSprint=null;for(const s of sessions){correct+=s.correct;total+=s.total;if(s.mode==="sprint"&&(!bestSprint||s.score>bestSprint.score))bestSprint=s;for(const st of s.categoryStats){const cur=map.get(st.category);if(cur){cur.correct+=st.correct;cur.total+=st.total}}}const categories=[...map.values()].map(e=>({...e,name:getCategory(e.category).name,accuracy:e.total?Math.round(e.correct/e.total*100):0}));return{sessionCount:sessions.length,practiceCount:sessions.filter(s=>s.mode==="practice").length,sprintCount:sessions.filter(s=>s.mode==="sprint").length,correct,total,accuracy:total?Math.round(correct/total*100):0,bestSprint,categories,weakest:categories.filter(e=>e.total).sort((a,b)=>a.accuracy-b.accuracy||b.total-a.total)[0]??null,strongest:categories.filter(e=>e.total).sort((a,b)=>b.accuracy-a.accuracy||b.total-a.total)[0]??null,recent:sessions.slice(0,6)}}
export function exportProgressData(sessions,leaderboard,bookmarks){return{product:"CodeClarity AI",exportedAt:new Date().toISOString(),disclosure:"This file contains browser-local coding practice results, leaderboard initials and bookmarked question IDs.",sessions:normalizeSessionsPayload(sessions),leaderboard:normalizeLeaderboardPayload(leaderboard),bookmarks:normalizeBookmarksPayload(bookmarks)}}
export function normalizeProgressImport(v){const p=typeof v==="string"?safeJsonParse(v,null):v;return p&&typeof p==="object"?{sessions:normalizeSessionsPayload(p.sessions),leaderboard:normalizeLeaderboardPayload(p.leaderboard),bookmarks:normalizeBookmarksPayload(p.bookmarks)}:null}
export const normalizeCoachNote=v=>normalizeMultiline(v,600);
