import { QUESTIONS } from "../content/questions.mjs";
import { QUESTION_PACKS } from "../content/packs.mjs";
import { CATEGORIES, DIFFICULTIES, getCategory } from "../content/categories.mjs";
import { clampNumber, isIsoDate, normalizeText, uniqueStrings } from "./text-core.mjs";
export const SESSION_VERSION=1,PRACTICE_DEFAULT_COUNT=8,SPRINT_QUESTION_COUNT=10,SPRINT_DURATION_SECONDS=90,WRONG_ANSWER_PENALTY_SECONDS=10;
const QM=new Map(QUESTIONS.map(q=>[q.id,q])),PM=new Map(QUESTION_PACKS.map(p=>[p.id,p])),CIDS=new Set(CATEGORIES.map(c=>c.id)),DIDS=new Set(DIFFICULTIES);
export const getQuestion=id=>QM.get(id)??null;
export const getPack=id=>PM.get(id)??PM.get("foundations")??QUESTION_PACKS[0];
export function toPublicQuestion(q){return q?{id:q.id,category:q.category,categoryName:getCategory(q.category).name,difficulty:q.difficulty,prompt:q.prompt,code:q.code??"",choices:[...q.choices],tags:[...q.tags]}:null}
export function hashString(value){let h=2166136261;for(const ch of String(value??"")){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function mulberry32(seed){let s=seed>>>0;return()=>{s+=0x6d2b79f5;let r=s;r=Math.imul(r^(r>>>15),r|1);r^=r+Math.imul(r^(r>>>7),r|61);return((r^(r>>>14))>>>0)/4294967296}}
export function seededShuffle(values,seed="codeclarity"){const random=mulberry32(hashString(seed)),copy=[...values];for(let i=copy.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}return copy}
export function selectQuestions({packId="foundations",categories=[],difficulty="mixed",count=PRACTICE_DEFAULT_COUNT,seed="codeclarity"}={}){const pack=getPack(packId);const cf=uniqueStrings(categories,{maxItems:CATEGORIES.length,maxLength:40}).filter(c=>CIDS.has(c));const cats=cf.length?cf:pack.categories;const diff=DIDS.has(difficulty)?difficulty:"mixed";const desired=Math.round(clampNumber(count,1,QUESTIONS.length,pack.questionCount));const categoryCandidates=QUESTIONS.filter(q=>cats.includes(q.category)),candidates=diff==="mixed"?categoryCandidates:categoryCandidates.filter(q=>q.difficulty===diff),pool=candidates.length?candidates:categoryCandidates;return seededShuffle(pool.length?pool:QUESTIONS,seed).slice(0,Math.min(desired,pool.length||QUESTIONS.length))}
export function evaluateAnswer(questionOrId,selectedIndex){const q=typeof questionOrId==="string"?getQuestion(questionOrId):questionOrId;if(!q)throw new TypeError("Unknown question.");const i=Number(selectedIndex),valid=Number.isInteger(i)&&i>=0&&i<q.choices.length,correct=valid&&i===q.correctIndex;return{questionId:q.id,selectedIndex:valid?i:null,correctIndex:q.correctIndex,correct,selectedChoice:valid?q.choices[i]:"",correctChoice:q.choices[q.correctIndex],explanation:q.explanation,rationale:valid?q.rationales[i]:"No answer was selected."}}
function catStats(ids,answers){const amap=new Map(answers.map(a=>[a.questionId,a])),stats=new Map();for(const id of ids){const q=getQuestion(id);if(!q)continue;const cur=stats.get(q.category)??{category:q.category,correct:0,total:0};cur.total++;if(amap.get(id)?.correct)cur.correct++;stats.set(q.category,cur)}return[...stats.values()].map(e=>({...e,accuracy:e.total?Math.round(e.correct/e.total*100):0})).sort((a,b)=>a.category.localeCompare(b.category))}
export function calculateScore({mode,correct,remainingSeconds=0}){const c=Math.max(0,Math.round(Number(correct)||0));return mode==="sprint"?c*100+Math.max(0,Math.round(Number(remainingSeconds)||0))*5:c*100}
export function createCompletedSession(input={}){const mode=input.mode==="sprint"?"sprint":"practice";const questionIds=uniqueStrings(input.questionIds,{maxItems:QUESTIONS.length,maxLength:80}).filter(id=>QM.has(id));const answers=Array.isArray(input.answers)?input.answers.filter(a=>a&&QM.has(a.questionId)).slice(0,questionIds.length).map(a=>({questionId:a.questionId,selectedIndex:Number.isInteger(a.selectedIndex)?a.selectedIndex:null,correct:Boolean(a.correct),answeredAt:isIsoDate(a.answeredAt)?a.answeredAt:new Date().toISOString(),elapsedMs:Math.round(clampNumber(a.elapsedMs,0,3600000,0))})):[];const correct=answers.filter(a=>a.correct).length,total=questionIds.length,remaining=Math.round(clampNumber(input.remainingSeconds,0,SPRINT_DURATION_SECONDS,0));const startedAt=isIsoDate(input.startedAt)?input.startedAt:new Date().toISOString(),completedAt=isIsoDate(input.completedAt)?input.completedAt:new Date().toISOString();const duration=Math.round(clampNumber(input.durationSeconds,0,86400,Math.max(0,Math.round((Date.parse(completedAt)-Date.parse(startedAt))/1000))));return{version:1,id:normalizeText(input.id,100)||`session-${Date.now()}`,mode,packId:getPack(input.packId).id,seed:normalizeText(input.seed,120),startedAt,completedAt,durationSeconds:duration,remainingSeconds:mode==="sprint"?remaining:null,questionIds,answers,correct,total,accuracy:total?Math.round(correct/total*100):0,score:calculateScore({mode,correct,remainingSeconds:remaining}),categoryStats:catStats(questionIds,answers)}}
export function getSessionReview(session){if(!session||!Array.isArray(session.questionIds))return[];const amap=new Map((session.answers??[]).map(a=>[a.questionId,a]));return session.questionIds.map((id,index)=>{const q=getQuestion(id);if(!q)return null;const a=amap.get(id)??{selectedIndex:null,correct:false};return{number:index+1,question:q,answer:a,evaluation:evaluateAnswer(q,a.selectedIndex),category:getCategory(q.category)}}).filter(Boolean)}
export function searchQuestions({query="",category="all",difficulty="all",limit=20}={}){const q=normalizeText(query,100).toLowerCase(),cat=CIDS.has(category)?category:"all",diff=DIDS.has(difficulty)?difficulty:"all",lim=Math.round(clampNumber(limit,1,50,20));return QUESTIONS.filter(item=>{if(cat!=="all"&&item.category!==cat)return false;if(diff!=="all"&&item.difficulty!==diff)return false;if(!q)return true;return[item.prompt,item.code??"",item.category,item.difficulty,...item.choices,...item.tags].join(" ").toLowerCase().includes(q)}).slice(0,lim)}
export function validateQuestionBank(){const issues=[],ids=new Set();for(const q of QUESTIONS){if(!q.id||ids.has(q.id))issues.push(`Duplicate or missing question ID: ${q.id}`);ids.add(q.id);if(!CIDS.has(q.category))issues.push(`Invalid category for ${q.id}`);if(!DIDS.has(q.difficulty))issues.push(`Invalid difficulty for ${q.id}`);if(!Array.isArray(q.choices)||q.choices.length!==4)issues.push(`Question ${q.id} must have four choices.`);if(!Number.isInteger(q.correctIndex)||q.correctIndex<0||q.correctIndex>=q.choices.length)issues.push(`Invalid correct index for ${q.id}`);if(!Array.isArray(q.rationales)||q.rationales.length!==q.choices.length)issues.push(`Rationale count mismatch for ${q.id}`);if(!normalizeText(q.explanation,1000))issues.push(`Missing explanation for ${q.id}`)}return issues}
