import test from "node:test";import assert from "node:assert/strict";import { QUESTIONS } from "../src/content/questions.mjs";import { createCompletedSession } from "../src/lib/quiz-core.mjs";import { addLeaderboardEntry,addSession,calculateProgress,exportProgressData,normalizeBookmarksPayload,normalizeInitials,normalizeLeaderboardPayload,normalizeProgressImport,normalizeSessionsPayload,toggleBookmark } from "../src/lib/progress-core.mjs";
function session(id,mode="practice",correct=2){const qs=QUESTIONS.slice(0,3),start="2026-01-01T00:00:00.000Z",end=`2026-01-01T00:00:0${id.length}.000Z`;return createCompletedSession({id,mode,packId:"foundations",seed:id,startedAt:start,completedAt:end,remainingSeconds:mode==="sprint"?15:0,questionIds:qs.map(q=>q.id),answers:qs.map((q,i)=>({questionId:q.id,selectedIndex:q.correctIndex,correct:i<correct,answeredAt:end,elapsedMs:1000}))})}
test("malformed or wrong-version session storage resets safely",()=>{assert.deepEqual(normalizeSessionsPayload("not-json"),{version:1,items:[]});assert.deepEqual(normalizeSessionsPayload({version:2,items:[session("x")]}),{version:1,items:[]})});
test("sessions deduplicate, sort and cap at forty",()=>{let p={version:1,items:[]};for(let i=0;i<45;i++)p=addSession(p,session(`session-${i}`));assert.equal(p.items.length,40);assert.equal(new Set(p.items.map(s=>s.id)).size,40)});
test("progress aggregates accuracy and identifies categories",()=>{const p=calculateProgress({version:1,items:[session("one", "practice",2),session("two","sprint",1)]});assert.equal(p.sessionCount,2);assert.equal(p.total,6);assert.equal(p.correct,3);assert.equal(p.accuracy,50);assert.ok(p.weakest);assert.ok(p.bestSprint)});
test("initials are trimmed, uppercased and bounded",()=>{assert.equal(normalizeInitials(" a-b12c "),"ABC");assert.equal(normalizeInitials("longname"),"LONG");assert.equal(normalizeInitials("r0yce!"),"RYCE");assert.equal(normalizeInitials("123"),"")});
test("leaderboard keeps valid sprint entries and caps twenty",()=>{let p={version:1,items:[]};for(let i=0;i<25;i++)p=addLeaderboardEntry(p,session(`s${i}`,"sprint",i%4),`A${String.fromCharCode(65+i%26)}`);assert.equal(p.items.length,20);assert.ok(p.items.every(x=>x.initials.length<=4));assert.ok(p.items.every((x,i,a)=>i===0||a[i-1].score>=x.score))});
test("bookmark state is allowlisted, deduplicated and capped",()=>{let p=normalizeBookmarksPayload({version:1,items:[QUESTIONS[0].id,QUESTIONS[0].id,"fake"]});assert.deepEqual(p.items,[QUESTIONS[0].id]);p=toggleBookmark(p,QUESTIONS[1].id);assert.ok(p.items.includes(QUESTIONS[1].id));p=toggleBookmark(p,QUESTIONS[1].id);assert.ok(!p.items.includes(QUESTIONS[1].id))});
test("export and import preserve only normalized local state",()=>{const s={version:1,items:[session("export")]},l=normalizeLeaderboardPayload({version:1,items:[]}),b=normalizeBookmarksPayload({version:1,items:[QUESTIONS[0].id]}),e=exportProgressData(s,l,b),n=normalizeProgressImport(JSON.stringify(e));assert.equal(n.sessions.items.length,1);assert.equal(n.bookmarks.items.length,1);assert.equal(n.leaderboard.items.length,0)});
