import test from "node:test";import assert from "node:assert/strict";import { QUESTIONS } from "../src/content/questions.mjs";import { calculateScore,createCompletedSession,evaluateAnswer,getQuestion,searchQuestions,seededShuffle,selectQuestions,toPublicQuestion } from "../src/lib/quiz-core.mjs";
test("seeded selection is deterministic and bounded",()=>{const a=selectQuestions({packId:"mixed-sprint",count:10,seed:"same"}),b=selectQuestions({packId:"mixed-sprint",count:10,seed:"same"});assert.deepEqual(a.map(q=>q.id),b.map(q=>q.id));assert.equal(a.length,10);assert.equal(new Set(a.map(q=>q.id)).size,10)});
test("difficulty and category filters are honoured",()=>{const q=selectQuestions({categories:["dom-events"],difficulty:"beginner",count:3,seed:"x"});assert.equal(q.length,2);assert.ok(q.every(x=>x.category==="dom-events"&&x.difficulty==="beginner"))});
test("evaluation returns verified answer data",()=>{const q=QUESTIONS[0],good=evaluateAnswer(q,q.correctIndex),bad=evaluateAnswer(q,(q.correctIndex+1)%4);assert.equal(good.correct,true);assert.equal(bad.correct,false);assert.equal(good.correctChoice,q.choices[q.correctIndex]);assert.ok(bad.rationale)});
test("public question omits answer and explanation",()=>{const p=toPublicQuestion(QUESTIONS[0]);assert.ok(!("correctIndex" in p));assert.ok(!("explanation" in p));assert.equal(p.choices.length,4)});
test("completed practice session calculates category evidence",()=>{const ids=QUESTIONS.slice(0,3).map(q=>q.id),answers=ids.map((id,i)=>({questionId:id,selectedIndex:getQuestion(id).correctIndex,correct:i!==2,answeredAt:new Date(0).toISOString(),elapsedMs:1000})),s=createCompletedSession({id:"session-one",mode:"practice",packId:"foundations",seed:"x",startedAt:new Date(0).toISOString(),completedAt:new Date(3000).toISOString(),questionIds:ids,answers});assert.equal(s.total,3);assert.equal(s.correct,2);assert.equal(s.accuracy,67);assert.equal(s.score,200);assert.equal(s.categoryStats[0].total,3)});
test("sprint score rewards correct answers and remaining time",()=>{assert.equal(calculateScore({mode:"sprint",correct:7,remainingSeconds:20}),800);assert.equal(calculateScore({mode:"practice",correct:7,remainingSeconds:20}),700)});
test("question search is literal and bounded",()=>{const r=searchQuestions({query:"event",category:"all",difficulty:"all",limit:4});assert.ok(r.length>0&&r.length<=4);assert.ok(r.some(q=>q.tags.includes("events")||q.prompt.toLowerCase().includes("event")));assert.doesNotThrow(()=>searchQuestions({query:"[.*",limit:5}))});
test("seeded shuffle does not mutate input",()=>{const source=[1,2,3,4],copy=[...source];seededShuffle(source,"x");assert.deepEqual(source,copy)});
