import http from "node:http";import { readFile,stat } from "node:fs/promises";import path from "node:path";import { fileURLToPath } from "node:url";import { spawnSync } from "node:child_process";import { handleCoach,handleHealth,handleQuestions } from "../src/server/handlers.mjs";import { readRequestBody } from "../src/server/http.mjs";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),".."),dist=path.join(root,"dist"),port=Number(process.env.PORT||4173);
try{await stat(path.join(dist,"index.html"))}catch{const r=spawnSync(process.execPath,[path.join(root,"scripts/build.mjs")],{stdio:"inherit",env:process.env});if(r.status!==0)process.exit(r.status??1)}
const types={".html":"text/html; charset=utf-8",".css":"text/css; charset=utf-8",".js":"text/javascript; charset=utf-8",".mjs":"text/javascript; charset=utf-8",".json":"application/json; charset=utf-8",".svg":"image/svg+xml",".png":"image/png",".xml":"application/xml; charset=utf-8",".txt":"text/plain; charset=utf-8",".webmanifest":"application/manifest+json; charset=utf-8"};
const redirects=new Map([["/index","/"],["/index.html","/"],["/quiz","/sprint/"],["/highscores","/leaderboard/"],["/highscores.html","/leaderboard/"]]);
function headers(type,pathname){return{"Content-Type":type,"X-Content-Type-Options":"nosniff","Referrer-Policy":"strict-origin-when-cross-origin","X-Frame-Options":"DENY","Cross-Origin-Opener-Policy":"same-origin","Cross-Origin-Resource-Policy":"same-origin","Cache-Control":pathname==="/sw.js"?"no-store":pathname.startsWith("/assets/")?"public, max-age=31536000, immutable":"no-cache"}}
function apiResponse(res,result){res.statusCode=result.status;for(const[k,v]of Object.entries(result.headers||{}))res.setHeader(k,v);if(result.ndjson){for(const event of result.ndjson)res.write(`${JSON.stringify(event)}\n`);res.end()}else res.end(result.body||"")}
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,"http://localhost"),p=url.pathname;if(redirects.has(p)){res.writeHead(308,{Location:redirects.get(p)});res.end();return}if(p==="/api/health"){apiResponse(res,await handleHealth({method:req.method,url:req.url,headers:req.headers,env:process.env}));return}if(p==="/api/questions"){apiResponse(res,await handleQuestions({method:req.method,url:req.url,headers:req.headers,env:process.env}));return}if(p==="/api/coach"){let body="";try{body=await readRequestBody(req,16384)}catch{body="x".repeat(16385)}apiResponse(res,await handleCoach({method:req.method,url:req.url,headers:req.headers,body,env:process.env}));return}let rel=p.replace(/^\/+/,"");if(!rel)rel="index.html";else if(p.endsWith("/"))rel+=`index.html`;let target=path.normalize(path.join(dist,rel));if(!target.startsWith(dist)){res.writeHead(403);res.end("Forbidden");return}try{const s=await stat(target);if(s.isDirectory())target=path.join(target,"index.html");const ext=path.extname(target);const data=await readFile(target);res.writeHead(200,headers(types[ext]||"application/octet-stream",p));res.end(data)}catch{const data=await readFile(path.join(dist,"404.html"));res.writeHead(404,headers(types[".html"],p));res.end(data)}}catch(error){res.writeHead(500,{"Content-Type":"text/plain; charset=utf-8"});res.end("Internal server error")}});
server.listen(port,()=>console.log(`CodeClarity AI running at http://127.0.0.1:${port}`));
